package com.hotmail.or_dvir.sabinesList.models

data class ListItem(
    val name: String,
    // generated by room (
    val listId: Int,
    val isChecked: Boolean,
    // generated by room
    val id: Int = 0
)