package com.hotmail.or_dvir.sabinesList.models

import java.time.LocalDate
import java.time.LocalTime

data class ListItem(
    val startDate: LocalDate,
    val endDate: LocalDate?,
    val startTime: LocalTime?,
    val endTime: LocalTime?,
    val note: String,
    // generated by room (
    val listId: Int,
    // generated by room
    val id: Int = 0
) {
    val hasEndDateTime = listOf<Any?>(endDate, endTime).any { it != null }
}
